# Generated by Django 2.1.15 on 2020-04-15 10:23

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Hotdeal',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('key', models.CharField(max_length=100)),
                ('target', models.CharField(choices=[('title', '제목'), ('content', '내용'), ('title_content', '제목 + 내용')], default='title', max_length=100)),
            ],
        ),
    ]
