# Generated by Django 3.0.5 on 2020-04-17 10:39

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Hotdeal',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('key', models.CharField(max_length=100)),
                ('target', models.IntegerField(choices=[(1, '제목 + 내용'), (2, '제목')], default=1)),
            ],
        ),
    ]
