# Generated by Django 2.1.15 on 2020-04-15 09:43

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Hotdeal',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('target', models.IntegerField(choices=[(1, '제목'), (2, '내용'), (3, '제목 + 내용')], default=1)),
            ],
        ),
    ]
